application:
  version: 1.0.0
  mode: development
kafka:
  bootstrapServers: localhost:9092,localhost:9093,localhost:9094
usecase:
  -
    className: com.stream.transactionlog.usecase.EnrichOrderUseCase
    active: true
    applicationID: transaction_tailing_local
    commitTime: 1000
    topics:
      orderTopic: orders
      orderDetailTopic: order_details
      aggregateTopic: combined-order-data
  -
    className: com.stream.transactionlog.usecase.EnrichCustomerUseCase
    active: false
    applicationID: transaction_tailing
    commitTime: 1000
    topics:
      customerTopic: sample.customer
      addressesTopic: sample.address
      aggregateTopic: combined-customer-data